### ISSUE TITLE
Azuracast Plugin

### ISSUE THREAD

**Issue by jjs999jjs** [SirJavik/Now-Playing-Widget-for-Azuracast-Stations#3]
Updated plugin today, 06/06/2020 now art no longer works

![image](https://user-images.githubusercontent.com/65810290/83949670-1b137780-a81d-11ea-8f38-566b9b91f5c5.png)

tried viewing in different browsers, same issue.

**Comment by SirJavik** [comment]
Hey, sorry for that late answer. I was a little inactive over the last weeks.
With Version 2.0.4 should anything fine now.
